package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func words() []string {
	return []string{"apple",
		"app",
		"ape",

		"hell",
		"hello",
		"hi",
		"howdy",
	}
}

func TestFindAll(t *testing.T) {
	tr := NewTrie()
	for _, v := range words() {
		tr.Add(v)
	}

	got := tr.findall()
	exp := words()

	assert.ElementsMatch(t, got, exp)
}

func TestFind(t *testing.T) {
	testCases := []struct {
		find string
		exp  []string
	}{
		{"ap", []string{"app", "ape", "apple"}},
		{"app", []string{"app", "apple"}},
		{"h", []string{"hi", "hello", "hell", "howdy"}},
		{"hello", []string{"hello"}},
		{"ho", []string{"howdy"}},
		{"hi", []string{"hi"}},
		{"hell", []string{"hell", "hello"}},
	}
	for _, tC := range testCases {
		t.Run(tC.find, func(t *testing.T) {
			tr := NewTrie()
			for _, v := range words() {
				tr.Add(v)
			}

			got := tr.FindPrefixed(tC.find)

			assert.ElementsMatch(t, got, tC.exp)
		})
	}
}

func TestFindEmpty(t *testing.T) {
	testCases := []struct {
		find string
	}{
		{"apc"},
		{"x"},
		{""},
		{" "},
	}
	for _, tC := range testCases {
		t.Run(tC.find, func(t *testing.T) {
			tr := NewTrie()
			for _, v := range words() {
				tr.Add(v)
			}

			got := tr.FindPrefixed(tC.find)

			assert.ElementsMatch(t, got, []string{})
		})
	}
}

func BenchmarkTrieFind(b *testing.B) {
	t := prepareTrieBenchInput()

	b.Run("Fetch all", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			t.findall()
		}
	})

	b.Run("Fetch a", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			t.FindPrefixed("a")
		}
	})

	b.Run("Fetch b", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			t.FindPrefixed("b")
		}
	})

	b.Run("Fetch hendrerit", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			t.FindPrefixed("hendrerit")
		}
	})
}

func BenchmarkTrieInitialisation(b *testing.B) {
	for i := 0; i < b.N; i++ {
		prepareTrieBenchInput()
	}
}

func prepareTrieBenchInput() *Trie {
	text := `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt venenatis ultricies. Aenean a magna rhoncus, molestie metus vel, fermentum sem. Vestibulum interdum nisi sit amet elit vehicula, id tristique erat dictum. Morbi magna sapien, tempus sed porta quis, euismod vel diam. Suspendisse ligula leo, aliquam et lacinia sit amet, molestie et magna. Proin tempor sem nec nibh lacinia rutrum. Donec et arcu eget velit efficitur interdum. Vestibulum laoreet bibendum ipsum, ac pulvinar erat imperdiet sit amet. Vivamus a lacus in lorem convallis cursus. Donec vitae lacus at dui faucibus suscipit. Curabitur eu mauris dictum, tincidunt lectus vitae, malesuada augue. Suspendisse bibendum, libero non convallis convallis, metus urna aliquam tellus, ac condimentum lacus sem a tortor. Sed euismod sollicitudin sem, vel molestie turpis pulvinar eget. Praesent fringilla libero in risus accumsan, at ullamcorper ligula molestie.
Nam ornare orci velit, vel blandit arcu iaculis sit amet. Nullam ex arcu, ultrices et consectetur eget, mattis at justo. Praesent sem risus, faucibus convallis venenatis nec, mattis gravida massa. Integer consequat diam vitae feugiat condimentum. Fusce eu molestie tortor. Donec sed velit ultricies, interdum nisi quis, maximus est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque scelerisque ante id ultricies. Maecenas tincidunt, orci in vulputate pretium, felis massa molestie neque, nec volutpat diam ex quis ex.
Duis vehicula, odio non hendrerit scelerisque, odio metus scelerisque tortor, vitae pellentesque tortor sem eu velit. Nunc at metus augue. Integer sit amet turpis sit amet tortor laoreet efficitur. Quisque bibendum massa ut auctor porta. Phasellus sapien tortor, faucibus vitae tempor sit amet, vulputate quis magna. Nullam justo metus, lacinia eu magna sit amet, fermentum ultricies augue. Morbi sapien urna, commodo vel augue in, rhoncus malesuada urna. Integer tortor massa, pellentesque sit amet nisl quis, commodo maximus risus. Pellentesque tempus gravida pellentesque. In vehicula dignissim velit eu lobortis.
Suspendisse augue orci, eleifend vitae pellentesque eget, pellentesque sit amet est. Duis auctor ipsum quis eros viverra luctus. Nam congue augue vitae ullamcorper lacinia. Maecenas euismod rhoncus neque feugiat maximus. Suspendisse in elit quis nisl molestie vulputate vitae id justo. Vestibulum in faucibus velit, eu pellentesque enim. Suspendisse tristique purus quis nulla dapibus dapibus. Curabitur varius ipsum ut ipsum suscipit, in semper tellus auctor. Sed aliquet magna neque, ut elementum sem ultricies a. Nam ultrices turpis mi. Fusce in dictum ante. Mauris lorem erat, sodales quis ex ut, ultricies consectetur purus. Ut eu enim at orci feugiat bibendum a in eros. Duis dignissim lorem at sem tempus, vitae mollis ante placerat.
Vestibulum ac odio a neque vehicula mollis at fringilla urna. Duis vel nisl lacinia, tristique magna nec, commodo nibh. Praesent porta tortor dapibus lobortis ultricies. Quisque et molestie justo. Integer pharetra odio ac ipsum pulvinar, faucibus blandit libero placerat. Nunc ac nisl ex. Aliquam vitae tortor interdum leo imperdiet pulvinar.
Proin non tortor a purus porta rutrum. Vestibulum sed ligula diam. Nam et ligula et nunc facilisis iaculis id quis velit. Suspendisse condimentum augue ut elementum fermentum. Etiam a purus accumsan, feugiat velit non, pellentesque lorem. Proin diam urna, placerat eget dictum ac, posuere consectetur ligula. Sed eget lobortis odio. Proin hendrerit ipsum quis aliquam mollis. Vestibulum luctus risus interdum magna dapibus bibendum. Phasellus eu euismod nisi. Praesent laoreet dolor vitae sollicitudin posuere.
Praesent nec nunc mauris. Nam facilisis massa eget risus tincidunt laoreet. Fusce sed porttitor nisl. Curabitur ac ullamcorper lacus, at laoreet velit. Nam vel tellus finibus, pretium nulla non, mattis magna. Phasellus tincidunt egestas quam quis tristique. Maecenas imperdiet libero erat, nec laoreet neque aliquet sit amet. Mauris varius faucibus mi, a euismod orci tincidunt eget. Vestibulum suscipit velit sapien, ut rutrum sapien posuere eget. Ut ornare semper lectus id pellentesque. Mauris id fringilla tellus, ut maximus libero. Sed eget scelerisque nibh, id dictum odio.
Aenean accumsan fermentum urna sagittis maximus. Mauris ipsum quam, tempus eu enim in, egestas suscipit mi. Nulla facilisi. Donec aliquam enim quis felis lacinia auctor. Cras aliquam commodo magna congue finibus. Aenean sed arcu sit amet elit pretium scelerisque. Proin ac diam ipsum. Phasellus orci dui, aliquam non purus at, fringilla euismod elit. Nulla congue tortor et tincidunt ornare. Morbi vulputate dolor in suscipit pellentesque. Mauris non sem sagittis, luctus turpis sit amet, suscipit magna. Pellentesque vel volutpat nunc, nec rhoncus arcu.
Phasellus quis sem diam. Quisque tortor leo, tincidunt sit amet placerat vel, elementum ut arcu. Quisque non hendrerit augue. Praesent tincidunt leo quis lacus cursus, sit amet iaculis erat pulvinar. Quisque a eros luctus, lacinia justo non, eleifend libero. Nullam mattis egestas consectetur. Praesent porta dolor tortor, eget cursus libero pretium et. Suspendisse volutpat mi eget suscipit aliquam. Aliquam erat volutpat. Suspendisse potenti. Nulla mattis nisi ex, vitae congue ex lobortis eget. Nunc posuere leo et tempor commodo.
Suspendisse fermentum auctor libero. Mauris accumsan tortor lectus, et pellentesque purus fermentum at. Aliquam nisl orci, porta in dolor ac, ultrices porttitor odio. In a accumsan ligula, vel molestie nunc. Vivamus fringilla vehicula sapien, a vehicula odio aliquet a. In fermentum, arcu a maximus blandit, sem dolor pharetra odio, eget faucibus augue augue et turpis. Phasellus dignissim rutrum elit non finibus. Morbi commodo, tellus quis imperdiet lacinia, sem felis rhoncus mi, id dignissim mauris odio elementum mauris. Cras sodales auctor turpis. Ut placerat scelerisque sapien, sed commodo elit consequat eu. Sed placerat enim justo, sed euismod tortor consectetur id.
Integer placerat magna ac blandit tristique. In hac habitasse platea dictumst. Proin rhoncus justo eu urna tincidunt, non egestas mauris tristique. Cras efficitur placerat dolor, in malesuada nisl varius ut. Pellentesque dictum, lacus a malesuada tempor, urna ante sodales quam, non gravida libero lectus ac velit. Phasellus libero nisl, auctor porttitor finibus nec, lobortis ac metus. Nulla sed ornare ante. Quisque sed tellus et lorem egestas pharetra ut sit amet turpis. Phasellus varius aliquet ornare. Proin tincidunt ligula quis lacus porta, eget tempus massa vehicula. Nunc tortor massa, venenatis id pharetra sit amet, egestas sit amet diam.
Integer eget nisi ut mauris faucibus tincidunt. Praesent vel imperdiet mauris. Praesent luctus sapien imperdiet mi auctor, luctus porttitor turpis viverra. Donec vel lorem tellus. Mauris tincidunt mi eget tempor congue. Nulla facilisi. Duis gravida rhoncus erat id euismod. Vestibulum hendrerit eu odio in venenatis. Phasellus non commodo diam. In efficitur finibus enim eu mollis. In non enim nunc. Phasellus mollis, leo ut maximus lobortis, turpis mauris ultricies eros, in pharetra justo lectus vel purus. Pellentesque tincidunt ultricies tellus ut semper. Sed sit amet placerat massa. Phasellus maximus felis eu risus fermentum vulputate. Phasellus sed vehicula diam.
Sed accumsan hendrerit felis, in semper nunc tempus ut. Aliquam ante nisl, pellentesque sed felis at, laoreet finibus lorem. Etiam ullamcorper ullamcorper libero in convallis. Quisque mattis at lacus eget feugiat. Cras enim orci, venenatis et nulla vel, tincidunt fermentum turpis. Donec sed dui neque. Pellentesque imperdiet diam elementum pharetra blandit. Proin nec luctus ante. Nam molestie nunc vitae risus porttitor rutrum. Fusce vitae ipsum congue, auctor lorem id, placerat augue. Phasellus ac lobortis libero, eu pulvinar nisi. Morbi diam ex, mollis ac velit et, faucibus ullamcorper urna. Integer convallis tempus risus, consectetur placerat risus scelerisque sit amet. Fusce tincidunt rutrum justo at molestie.
Donec imperdiet at nulla in tincidunt. Phasellus interdum mauris id augue aliquam, eu accumsan nunc condimentum. Nam auctor nec magna nec lobortis. Donec faucibus enim et ultrices rhoncus. Nullam quis erat diam. In hac habitasse platea dictumst. Phasellus facilisis risus in mauris vulputate pretium. Nullam rutrum eros enim, sed sodales orci tincidunt vulputate. Suspendisse potenti. Cras sollicitudin, elit ac ultrices viverra, velit libero maximus sapien, sit amet posuere diam tellus at felis. Nullam eget tellus sit amet tortor laoreet tincidunt. Mauris imperdiet nunc ut dolor ultricies blandit. Fusce a ultricies massa, id luctus urna. Donec quis suscipit erat. Curabitur molestie ullamcorper libero, id ultricies lacus iaculis quis. Nullam et scelerisque leo, sodales dapibus est.
Donec eros ipsum, finibus eget ipsum non, pulvinar accumsan ipsum. Duis eu viverra velit, vel molestie erat. Curabitur fringilla elit finibus lorem interdum, id aliquet velit fringilla. Curabitur tincidunt lorem at blandit tincidunt. Etiam cursus diam quis turpis posuere, ultricies sollicitudin dui imperdiet. In vehicula bibendum pretium. Aenean enim lorem, egestas in lectus pellentesque, sodales semper dui. Phasellus accumsan ligula sit amet diam ullamcorper, quis malesuada libero pretium. Fusce sagittis ac neque eget aliquet. In vulputate volutpat diam eget cursus. Sed nec venenatis orci. Suspendisse nec egestas mi, et venenatis urna. Duis ornare metus vehicula nibh ultrices, a congue mauris egestas. Vestibulum et justo sit amet enim tincidunt elementum.
Quisque pharetra in urna bibendum congue. Ut at sapien auctor, sodales enim a, fringilla ex. Etiam ultrices lectus tellus, non tristique ex fermentum ut. Duis pellentesque maximus tincidunt. Praesent est quam, pretium eget elementum non, mattis in enim. Etiam luctus a quam eget vestibulum. Proin sit amet blandit leo, in tincidunt lectus. Sed commodo volutpat tellus ac consequat. Ut ullamcorper, augue id sollicitudin tincidunt, leo nibh molestie lacus, ac porttitor erat sapien in nibh.
Aenean at lectus elementum, gravida erat a, maximus lacus. Quisque in bibendum neque. Etiam euismod finibus elit quis vulputate. Aliquam maximus nisi sit amet neque convallis ultricies. Vivamus eu sapien sit amet nunc ullamcorper venenatis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec quis justo elit. Cras in ante at odio laoreet gravida. Integer interdum arcu ac mattis feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque accumsan placerat quam, vel volutpat ligula euismod eget. Etiam in eros purus. Nunc iaculis in mi sed fringilla.
Aenean at gravida turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rutrum pretium purus, ac mattis ipsum consequat id. Donec eleifend at ante a semper. Mauris elementum erat lectus, eu condimentum mauris aliquam nec. Quisque vestibulum imperdiet dolor non euismod. Vestibulum tortor quam, molestie non ante a, bibendum viverra ante. Maecenas mattis arcu et ante scelerisque, eget porttitor mi pretium. Mauris luctus eros cursus pellentesque fringilla. Etiam magna arcu, molestie non fringilla ac, facilisis sit amet leo. Pellentesque at sem facilisis, accumsan eros ut, lacinia nulla. Sed feugiat tincidunt volutpat. Proin bibendum lorem laoreet massa feugiat, quis aliquam ligula facilisis.
Etiam vel nulla volutpat, ullamcorper felis quis, ultricies orci. Aliquam ac dolor viverra, congue lacus vel, efficitur tortor. Donec rhoncus nisi at elit molestie ultrices. Maecenas ac egestas diam. Donec convallis gravida lorem, nec commodo ligula placerat a. Fusce sed lectus ac tellus aliquet placerat at at erat. Fusce pretium, lectus quis laoreet fringilla, velit ex tempor nibh, sit amet fringilla leo mauris a tortor. Vestibulum rutrum ultrices libero ut dapibus. Integer tincidunt diam ut dolor vehicula, id consequat velit mollis. Morbi quis ultrices massa. Maecenas quis eleifend lorem. Nullam lobortis molestie facilisis. Mauris velit enim, consequat eget enim sit amet, aliquet scelerisque metus. Morbi bibendum euismod risus, at posuere est tempus lobortis.
Nunc porttitor dictum ante a ultrices. Cras pellentesque tortor a sem aliquet lobortis. In blandit odio ligula, vitae tincidunt quam semper et. Vestibulum auctor ante luctus diam semper, id bibendum justo convallis. Maecenas vel purus non elit convallis elementum. Praesent hendrerit, orci vel tristique posuere, tellus nisl ultrices leo, vel hendrerit orci neque a est. Vestibulum non lorem ante.
Nam in mattis velit, eget fermentum ex. In hac habitasse platea dictumst. Curabitur vel massa nec sapien placerat dapibus. Vestibulum non pretium ligula. Fusce vel sagittis quam, nec auctor elit. Cras id massa massa. Suspendisse semper venenatis nisl vitae placerat. Donec a nulla risus. Quisque condimentum felis eu dolor tincidunt congue. Praesent elementum tempus nisl sit amet euismod.
Sed eu nibh vehicula, dapibus tortor at, venenatis tortor. Pellentesque efficitur porttitor arcu, in egestas leo varius sed. Integer maximus dapibus mattis. Nunc non sollicitudin risus. Quisque et tincidunt nisi. Donec consequat mi non placerat pharetra. Donec tristique tincidunt neque.
Suspendisse potenti. Sed a porttitor eros. Integer lorem dolor, consectetur a finibus at, aliquam non ante. Aliquam egestas, sem nec lobortis bibendum, erat tortor interdum nulla, sed viverra leo urna sit amet augue. Curabitur malesuada massa vel maximus sollicitudin. Nulla mollis nisl non auctor posuere. Nullam faucibus condimentum massa eget lacinia. Sed vitae nulla et felis pulvinar vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras facilisis erat mauris, a varius nisl viverra et. Ut bibendum turpis vitae est tincidunt, ac tristique leo porttitor. Duis vehicula, ipsum ut lacinia pellentesque, arcu lectus vestibulum massa, eget semper turpis orci vel sapien. Sed at purus volutpat, maximus odio pulvinar, aliquam mi.
Proin sodales, diam sit amet varius tempor, tellus ipsum congue turpis, eleifend vestibulum tellus eros et lectus. Suspendisse faucibus lobortis velit vel ultricies. In non augue vitae neque semper condimentum ac sit amet nisl. Duis pulvinar nisl eu faucibus auctor. Integer convallis, enim ut ultrices gravida, est massa dapibus odio, ut suscipit tortor quam vel lorem. Fusce nisi orci, maximus eget fringilla sit amet, venenatis a libero. Nullam sed neque eget lorem lobortis vulputate. Fusce vitae pharetra magna. Sed a hendrerit dui, sit amet pellentesque urna. Sed condimentum ac orci et molestie. Donec vel tortor tortor. Phasellus accumsan sodales urna, sit amet vestibulum mauris dignissim ut. Quisque faucibus eget ante sit amet condimentum.
Maecenas cursus ultrices risus sit amet tincidunt. Mauris fringilla sed odio vel pretium. Nunc tristique nunc non lobortis cursus. In dapibus mollis placerat. Etiam eu iaculis mi. Nunc lacus neque, placerat ut commodo ut, rutrum nec nulla. Morbi venenatis ipsum ut mi faucibus imperdiet.
Nam in orci ullamcorper, egestas odio a, rutrum nibh. Aliquam erat volutpat. Vivamus tincidunt erat at imperdiet accumsan. Fusce efficitur consectetur ipsum, nec tincidunt enim suscipit mollis. Etiam commodo purus nec blandit lacinia. Cras tincidunt, erat vitae sagittis tincidunt, mi lectus molestie velit, eget vulputate ex quam nec eros. Curabitur vitae suscipit enim, vitae rutrum lectus.
Phasellus suscipit turpis magna. Sed est odio, molestie et congue in, elementum non massa. Praesent ut blandit tellus. Vivamus tincidunt, ex sit amet volutpat feugiat, nisi dui porta eros, nec consequat elit mi sit amet erat. Donec in nibh aliquet, dapibus ligula bibendum, gravida eros. Nunc fermentum mi lectus, non lobortis ante molestie eget. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam augue turpis, fermentum eu nibh eget, vehicula gravida neque. Praesent gravida maximus eros, nec consectetur arcu iaculis ac. Proin sagittis vulputate lectus, et molestie neque faucibus sit amet. Nam porta orci eu aliquam volutpat. Proin ut arcu ante. Duis in lobortis elit.
Nam vel nulla urna. Etiam vitae diam pulvinar, iaculis enim vitae, posuere leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi neque ligula, commodo quis aliquet in, dictum sed nisi. Aliquam sollicitudin lectus vitae diam dignissim, id efficitur eros egestas. Integer laoreet odio vitae dui vestibulum, facilisis gravida lacus condimentum. Nam et sapien in felis bibendum tempor id et dui. Nam sit amet fringilla leo. Nullam nisl urna, commodo vitae ante ac, lobortis euismod diam. Proin quis risus efficitur, semper orci in, sodales velit. Vivamus fringilla, nunc sed tincidunt sodales, sapien dui facilisis nisl, nec semper neque diam eu mi. Mauris et est ut arcu volutpat ultrices vehicula a nulla. Donec et ipsum ut justo bibendum cursus eu sit amet massa. Duis in orci quis est vehicula egestas. Sed hendrerit velit est, at interdum arcu vulputate vel. Aenean vestibulum aliquam sem id interdum.
Aenean rhoncus facilisis nulla, id pulvinar augue. Quisque at dapibus lorem, tincidunt fringilla odio. Etiam dolor urna, aliquam eu faucibus eu, tincidunt at erat. Integer at libero ultrices, blandit odio non, accumsan elit. Nunc risus leo, dictum nec metus vitae, venenatis vestibulum risus. Integer in purus porttitor enim blandit ornare non sit amet dui. Ut a sem ac ipsum tincidunt lacinia sit amet sed ante. Cras urna odio, tempor ut risus nec, dignissim egestas tortor. Phasellus facilisis bibendum ante pulvinar tempus. Nam ut dignissim neque. Etiam quis dui lorem. Sed eleifend velit neque, eget molestie felis tristique id. Quisque sit amet enim tincidunt, tempus odio vitae, commodo massa.
Nunc non lacinia lorem. Suspendisse dapibus faucibus mi vel pellentesque. Sed at lectus maximus, commodo odio a, faucibus risus. Curabitur eu magna et turpis faucibus tincidunt sit amet in nibh. Ut dignissim quam et lectus convallis semper. Praesent dignissim, magna vel auctor tristique, velit massa convallis neque, non blandit justo nunc eu leo. Morbi ultricies urna arcu. Nulla lacinia fringilla tempus. Sed congue libero quis neque pulvinar, et posuere ipsum ultrices. Vivamus lacinia accumsan lacus eu euismod. Nullam ac venenatis velit, eget malesuada magna. Cras finibus risus ut odio hendrerit, non aliquet dolor laoreet.
Curabitur molestie dignissim odio, a tincidunt enim iaculis consequat. Curabitur et lacus sit amet libero condimentum commodo eget non lectus. Aenean libero leo, finibus eu mi in, fermentum bibendum augue. Proin eget ipsum eget velit eleifend commodo vel eget leo. Phasellus sit amet lacus pretium, scelerisque erat consequat, tempus massa. Nunc dapibus arcu id ligula imperdiet aliquam. Mauris condimentum, mauris et congue luctus, libero tortor hendrerit augue, ac condimentum neque lacus consectetur turpis. Vivamus sem dui, dapibus non nunc a, posuere finibus lectus.
Nam in metus non metus placerat scelerisque. Nulla congue ipsum sed erat tempor viverra. Ut vel leo venenatis, egestas lorem et, commodo lorem. Nam eget venenatis odio, ac pellentesque quam. Morbi molestie felis eget eleifend faucibus. Nulla gravida interdum nibh, vitae fringilla elit hendrerit sed. Phasellus tristique lacus sed est fringilla ullamcorper. Fusce arcu tortor, rhoncus maximus ipsum id, dapibus accumsan elit.
Sed vulputate neque ullamcorper finibus molestie. Aliquam non tellus volutpat, ultricies tellus in, vehicula metus. Nullam pretium congue sodales. Maecenas in porttitor odio. Aenean mattis ullamcorper ante, ac sodales quam cursus id. Duis a fermentum ante, aliquam scelerisque dolor. Nunc maximus at urna sollicitudin convallis. Phasellus massa ligula, luctus vel convallis ac, dapibus quis sapien.
Etiam pharetra leo eget leo convallis, in rhoncus mauris porttitor. Nunc ipsum nisi, ultrices in sapien a, viverra vulputate sem. Duis at mauris eleifend, porta turpis eget, bibendum neque. Etiam in suscipit purus. Donec eu consequat sapien. Aliquam at eros vitae neque posuere malesuada non a velit. Curabitur facilisis molestie pharetra. Sed erat magna, interdum nec velit sit amet, posuere feugiat ligula. Suspendisse ornare odio ac imperdiet maximus. Quisque facilisis elementum fringilla. In dolor enim, efficitur at nisi feugiat, ultrices pulvinar justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
Donec ut vestibulum mi. Maecenas sit amet tellus sit amet ipsum ultricies suscipit. Praesent ac laoreet erat. Nulla justo nulla, consectetur vel hendrerit sit amet, blandit eget nulla. Fusce est nibh, consectetur et tortor sed, scelerisque fermentum orci. Sed quis mattis ante, vitae egestas turpis. Duis eu nulla porta, rhoncus risus sit amet, facilisis massa. Nulla viverra hendrerit mauris dictum elementum. Mauris varius diam ultrices nunc consequat facilisis. Proin a dictum nulla, ultrices dignissim augue. Mauris iaculis porta tristique. Vestibulum gravida euismod tortor. In viverra ante vel varius ullamcorper. Cras et blandit risus.
Nam lobortis mattis augue. Phasellus suscipit placerat sem, id pharetra felis tincidunt a. Donec malesuada, ligula nec pharetra volutpat, elit est rutrum ante, vel porta ipsum justo et nisl. Fusce tincidunt odio quis urna sagittis hendrerit. Cras et enim finibus, pretium nulla eu, congue dui. Duis sagittis facilisis orci et faucibus. Quisque porta tortor et tellus tincidunt, eget malesuada purus bibendum.
Nulla ligula nunc, imperdiet non ultricies vel, laoreet sit amet purus. Aenean eget pharetra neque, at semper magna. Nunc lacus arcu, porttitor nec lacus ut, dictum facilisis nulla. Suspendisse feugiat eget velit eget sodales. Nam in nisi lorem. Cras finibus aliquam ante et bibendum. Mauris finibus justo quis erat porta vulputate vitae non nibh. Nam pulvinar magna eget lectus varius ultricies. Ut ac nunc porta, aliquet massa et, convallis tortor. Etiam molestie massa in tempor feugiat. Donec convallis hendrerit justo, eu scelerisque urna tincidunt ut. Quisque ac consequat orci. Proin vestibulum, lectus sed interdum cursus, risus sem elementum urna, in aliquet nisi nulla quis odio. Duis non tincidunt justo, at suscipit dui. Duis sed ligula porttitor, interdum ante vitae, lacinia libero. Maecenas mi nisl, fringilla vel hendrerit vitae, eleifend non tortor.
Pellentesque viverra iaculis mi. Sed accumsan posuere tristique. Quisque non molestie nibh, et sagittis eros. Proin tincidunt aliquet pellentesque. Nam rhoncus egestas elit nec pretium. Etiam vestibulum ligula at suscipit euismod. Vestibulum vulputate risus leo, non feugiat augue condimentum sit amet. Curabitur sodales erat risus, finibus sollicitudin ex viverra ac. Phasellus tincidunt, orci eget dictum faucibus, metus nulla egestas nulla, nec posuere mauris nulla sit amet dui.
Fusce a rhoncus erat, vel elementum erat. Nam tellus sem, mollis gravida ante id, elementum consectetur justo. Aliquam laoreet lacinia sollicitudin. Morbi commodo, augue in finibus dapibus, erat turpis ultricies neque, in pharetra eros erat non ante. Ut lacinia, augue sed molestie tempus, nibh justo rhoncus urna, vel sollicitudin erat purus porta nunc. Morbi commodo est ut velit tempus porta. Nulla facilisi. Nulla ac vulputate nunc. Maecenas sit amet placerat urna, in commodo enim. Curabitur ac sapien consequat, suscipit lectus ut, aliquet tellus. Sed neque mauris, egestas eu ullamcorper ac, facilisis ut lorem. Vestibulum nisi nisl, scelerisque in augue quis, aliquet vehicula augue. Duis pellentesque varius velit sit amet luctus. Fusce malesuada, arcu at tincidunt faucibus, augue arcu gravida velit, eu viverra lectus sem vel ligula.
Duis posuere tincidunt dui. Aenean sit amet tincidunt nibh, eget rutrum risus. Suspendisse dignissim consequat sapien et egestas. Etiam dictum arcu vitae sapien facilisis finibus. Curabitur sed mi ac nisi mattis ultrices. Praesent semper molestie nisl vitae accumsan. Donec est risus, hendrerit ac blandit vel, convallis ac tortor.
Pellentesque venenatis odio non magna mollis venenatis. Proin eleifend urna erat, sed iaculis urna blandit tempus. Aenean nec bibendum sapien, eget egestas mauris. Pellentesque et massa quis nibh varius pellentesque. Pellentesque commodo risus et tellus auctor ultrices. Vivamus vel pellentesque arcu. In neque lacus, tincidunt vel rhoncus non, fermentum id sem. Aenean eget tincidunt nisi. Vestibulum a metus purus.
Curabitur pharetra id dolor eget facilisis. Nam sit amet nulla vel leo pretium rhoncus nec a neque. Donec quis sagittis arcu. Fusce ac sem sed tellus vulputate iaculis id auctor tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam sodales diam felis. Nullam et nisi non orci consectetur facilisis vitae sed ex. Integer efficitur ipsum sed tellus blandit, quis euismod tellus tincidunt. Suspendisse dignissim est quis ante volutpat pellentesque. Nulla facilisi. Nunc lobortis consectetur viverra. Suspendisse laoreet ipsum risus, eget blandit velit lacinia ac.
Etiam metus massa, euismod nec vulputate ac, ullamcorper tristique enim. Pellentesque in tellus nulla. Ut quis eleifend risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus eu orci lectus. Sed vel turpis sit amet urna faucibus mattis. Maecenas in elementum massa. Etiam malesuada massa quis elit interdum vestibulum. Donec pretium ultrices mauris quis tristique. Proin suscipit nibh quam, vel volutpat metus placerat et. Phasellus posuere eu tellus et eleifend. Pellentesque dapibus diam velit, sed lacinia odio dictum in. Aenean tincidunt, magna et sagittis fermentum, odio ante fringilla elit, ut viverra enim mi sed nunc.
Proin non commodo diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum sit amet imperdiet nunc. Vivamus eget est id nisl scelerisque auctor nec quis mi. Vestibulum iaculis vulputate pellentesque. Maecenas elementum condimentum mauris, in aliquam ligula ultricies consectetur. Fusce pharetra pharetra felis, vel ornare lacus consectetur quis. Vestibulum ultrices urna vel ex convallis condimentum. Vestibulum eu enim tellus. Mauris auctor interdum quam, vitae sodales sem tincidunt eget. Proin sit amet tempor ante. Aliquam maximus pellentesque enim, eget ullamcorper sem consectetur sed. Etiam et dui eleifend, blandit nisl ac, gravida odio. Nullam non ligula venenatis, bibendum erat vitae, efficitur tellus. Nulla mattis nunc non augue ultrices ornare.
Sed facilisis, diam sed sodales eleifend, nulla nulla ullamcorper erat, nec auctor purus est auctor tellus. Ut ac dui dictum, facilisis nisl vel, molestie nisi. In sapien quam, viverra quis magna eget, commodo dapibus nunc. Etiam viverra ante a ligula pulvinar faucibus. Vestibulum pretium hendrerit efficitur. In et mi sapien. Nullam laoreet accumsan tellus, eu rutrum justo condimentum eget. Donec bibendum pellentesque odio et viverra. Nunc ornare orci ac ipsum laoreet, vel fringilla lorem hendrerit. Duis ac dignissim tellus, sed tincidunt eros. Etiam nec dapibus est, vel egestas nunc. Proin eleifend sem dictum, fermentum mi sagittis, lobortis metus. Donec porttitor elementum tempus.
Cras eu sollicitudin mauris. Aliquam eu rutrum nunc. In a nunc nisi. Phasellus mattis interdum nisi, eget venenatis dolor tincidunt placerat. Pellentesque nec neque ipsum. Morbi mauris lorem, tristique at pellentesque id, convallis quis tortor. Aliquam arcu ligula, vulputate eget eleifend ut, porttitor sit amet orci. Praesent tempor, mi sed tristique facilisis, metus lacus feugiat erat, at pellentesque quam nisi sit amet erat.
Phasellus mi lectus, vestibulum id bibendum sed, suscipit a quam. Integer quis porttitor ipsum, sit amet vestibulum enim. Mauris viverra ullamcorper tortor, eget rhoncus nulla sodales vel. Aenean consequat aliquet tempor. Cras lectus eros, egestas nec condimentum et, interdum quis nibh. Nullam vel vehicula neque, volutpat maximus sem. Maecenas fermentum commodo ipsum, accumsan consequat dui vehicula ut. Etiam eu lacus lacus. Phasellus libero enim, iaculis vel erat in, porttitor efficitur nulla. Nullam vitae rhoncus lectus, id mattis mi. Cras mattis vitae elit ut dignissim. Sed mattis faucibus mi ut rhoncus. Quisque turpis mi, dignissim et nulla eget, euismod lacinia purus. Morbi gravida quam et feugiat porttitor. Suspendisse feugiat ex mauris, in euismod purus elementum vitae. Etiam faucibus ipsum quis venenatis finibus.
Sed vel risus massa. Nam pulvinar aliquam molestie. In vel eros ipsum. Nam convallis leo euismod ex facilisis vulputate. Sed fringilla erat vel sodales blandit. Etiam ut sem urna. Nam consequat, enim non tempus congue, eros quam efficitur erat, eget euismod odio erat in justo. Nam sed ullamcorper ligula. Vestibulum sodales lacus nec luctus elementum. Fusce non felis quam. Aenean ultricies venenatis massa vitae tincidunt. Praesent elementum libero vitae venenatis maximus. In eleifend lacinia sem, sed fermentum elit bibendum et.
In at nibh vitae purus pretium hendrerit in ac turpis. Maecenas sit amet blandit augue, non accumsan lectus. In egestas purus sed ornare commodo. Sed sit amet lacus tempus, facilisis odio at, egestas felis. Sed nec justo malesuada, blandit neque vel, vulputate massa. Donec luctus dictum diam in faucibus. Aenean maximus aliquam lectus quis fermentum. Mauris pulvinar efficitur est, ut vestibulum tortor. Nullam suscipit orci sit amet elit mattis finibus. Pellentesque id consectetur felis. Nunc eget arcu nunc. Sed placerat purus eget cursus molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras ac auctor ante. Donec ultrices, purus nec bibendum lacinia, ante purus maximus lacus, ac tempus velit elit et dolor. Morbi cursus risus felis, eget semper enim feugiat non.
Sed cursus, ex sit amet rhoncus imperdiet, sem ex ornare lacus, sit amet dapibus elit enim vehicula ipsum. Cras aliquet laoreet tellus. Nunc hendrerit, elit eleifend imperdiet sodales, nunc ligula mollis leo, a scelerisque justo ipsum id ipsum. Vivamus lacinia magna ac porta dapibus. Proin quis cursus lectus, ac tempus nibh. Integer luctus, tortor volutpat tempor tempus, est dui mattis sapien, in elementum arcu metus sit amet justo. Donec congue orci nulla, vel facilisis dui laoreet rhoncus. Sed fringilla diam non luctus ornare. Proin ut turpis porta, fermentum lacus sed, finibus quam. Duis nec mi et felis maximus tempor et tincidunt erat. Praesent vel malesuada metus, a sagittis nulla. Praesent molestie blandit magna lacinia tempor. Mauris odio eros, pulvinar quis tincidunt vitae, imperdiet venenatis ipsum.
Donec sollicitudin nisl nec lorem sagittis, a lobortis magna faucibus. Phasellus at massa et sapien lobortis lacinia. Praesent at elit vel est sodales maximus et suscipit mauris. Vivamus ac consequat erat. Proin maximus tincidunt laoreet. Sed tortor nunc, posuere nec quam ac, porta lacinia lorem. Sed augue dolor, feugiat vestibulum vehicula at, tempus ac risus. Nulla dapibus erat in arcu fermentum, aliquam elementum ligula mattis. Sed posuere lacinia felis a pulvinar. Proin aliquam vehicula justo, sed eleifend magna semper sit amet. Cras rutrum erat quis nisl ultrices, vel faucibus nisl fringilla. Etiam pharetra ante risus, non dictum tellus accumsan in. Morbi placerat elementum leo, nec molestie magna gravida accumsan. Aliquam sit amet nibh magna.
Donec ante lacus, porttitor quis orci vitae, hendrerit fermentum dolor. Nulla maximus dolor eu hendrerit venenatis. Nullam posuere, mauris id posuere porta, ligula arcu efficitur massa, at mollis neque nisi id magna. Mauris accumsan placerat turpis, ac lobortis risus eleifend at. Quisque sit amet interdum erat, eu convallis est. Maecenas at erat enim. Sed malesuada finibus orci vel consequat. Duis ligula erat, tempor nec lorem eu, vulputate congue arcu. Proin ut pellentesque magna. Mauris porta consequat ipsum. Donec blandit enim nulla, consectetur tristique leo bibendum at. Nam id semper massa, nec fermentum nulla.
Suspendisse potenti. Integer tempus vitae sapien a mollis. Nam sollicitudin gravida neque, sed luctus velit commodo et. Morbi euismod lectus nec euismod maximus. Nulla non molestie metus. Donec commodo ipsum ac orci vehicula tempor vel ac lectus. Maecenas suscipit interdum mauris ut auctor. Nam non tempor lectus, sed sodales lorem. Aenean in ex mollis, feugiat eros a, vulputate nisl.
Nulla facilisi. Ut nec metus mollis, volutpat odio vitae, pretium mauris. Sed aliquet ullamcorper nulla, interdum malesuada purus suscipit in. Mauris fermentum tortor non purus facilisis, eget eleifend purus vulputate. Praesent et dui nibh. Nulla facilisi. Nunc non aliquam felis. Nullam blandit vulputate tellus non maximus. Aenean tristique a eros non feugiat.
Duis cursus lectus quam, posuere auctor massa egestas eget. Vivamus ut mollis lorem. Nunc ante sem, placerat sed pharetra sed, congue id justo. Proin tempor convallis leo non imperdiet. Pellentesque ultricies lacus ipsum, sit amet consequat dui consectetur at. Vestibulum mollis pulvinar nulla, sit amet sagittis lectus efficitur sed. Pellentesque malesuada magna eget nisl tempor, quis vulputate libero suscipit. Pellentesque vestibulum felis eu laoreet luctus. Etiam vestibulum molestie elit, rhoncus dictum urna efficitur ac. Duis nulla massa, mollis eget pharetra vitae, vulputate ac elit. Suspendisse mollis felis id orci feugiat, ac condimentum magna malesuada. Aliquam nec nisi et purus condimentum blandit. Pellentesque eget rhoncus lorem. Aenean orci est, mollis ut bibendum vel, suscipit et quam. Morbi ut nibh maximus, ultricies erat at, malesuada ipsum. Mauris tempus risus efficitur ultrices condimentum.
Proin eget cursus lacus. Proin odio nisl, mollis ut arcu vel, pretium luctus ligula. Vivamus porta quam ut augue gravida, sit amet pellentesque nisl sodales. Ut quis tortor nisi. Nunc sed convallis metus, in luctus libero. Donec dignissim lacus lorem. Aliquam ultricies nisi id sem luctus placerat. Donec libero ex, faucibus nec tristique ac, efficitur sit amet eros. Vivamus in ipsum quis erat mattis volutpat vitae fermentum purus. Suspendisse eu bibendum massa. Nunc placerat erat at auctor iaculis. Fusce porttitor, lacus tincidunt imperdiet porttitor, arcu enim posuere neque, ut convallis odio tellus eu erat. Nulla condimentum sit amet eros ut condimentum. Aenean vel nibh fringilla, fringilla ex at, dictum velit.
Aenean consequat luctus lacinia. Phasellus sed libero risus. Nunc porta viverra nibh, lacinia tincidunt arcu suscipit id. Cras blandit laoreet dolor, eget euismod nibh elementum in. Aliquam quis velit viverra, blandit sem aliquam, tempus sapien. In maximus interdum ex, vel mattis erat aliquet quis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse ut felis eu risus consectetur congue vel id nibh. Pellentesque nulla augue, ullamcorper in hendrerit at, fringilla vitae elit. Maecenas eu vulputate nisi. Nunc egestas felis vitae urna pellentesque ultrices. Morbi quis blandit orci. Aliquam id laoreet lacus. Ut eros dui, porta a bibendum et, tempor vel leo.
Phasellus non elit non elit mollis ullamcorper ut a dolor. Nulla a fringilla magna. Quisque commodo mattis neque, ac luctus metus imperdiet quis. Sed at porta est. Quisque auctor sit amet diam nec tincidunt. Morbi vehicula sapien ut nisi aliquam tincidunt. Maecenas aliquam felis eget libero hendrerit, eu mattis justo ornare. Mauris nec dolor venenatis, venenatis risus id, euismod enim. Suspendisse eget suscipit diam, sit amet dapibus quam. Duis placerat erat sed posuere efficitur. Nulla velit magna, mollis in interdum et, porttitor quis lacus. Nulla nunc sapien, faucibus ut nulla a, pellentesque cursus felis. Nulla id tellus fringilla leo cursus rhoncus sed eu lectus. Aliquam id est purus. Nam ultricies ex ut nulla aliquam, ac facilisis eros ultricies. Integer consectetur in neque vitae varius.
Nulla tortor lacus, condimentum a lorem in, pellentesque lobortis magna. Donec mattis neque vitae risus suscipit eleifend. Curabitur aliquet ipsum sollicitudin facilisis laoreet. Duis placerat lacus vulputate lectus auctor, quis placerat leo suscipit. Vestibulum in pretium massa. Aliquam faucibus turpis porta felis laoreet, vitae interdum nisl blandit. Maecenas odio dolor, pretium in augue a, pulvinar ultricies est. Morbi in tellus aliquam, volutpat nulla eu, faucibus velit.
Maecenas luctus quis arcu venenatis blandit. Sed maximus molestie leo mollis tempor. Vestibulum hendrerit finibus est at efficitur. Nullam eu nisi non augue hendrerit aliquam in a lorem. Nunc tincidunt, velit quis finibus scelerisque, nisi risus consectetur lectus, sed cursus dolor metus nec ligula. Fusce fermentum metus eu rhoncus laoreet. Sed at fermentum lorem. Cras eget finibus nisi. Quisque tempus ultricies ex, ac aliquet velit scelerisque non. Fusce posuere elit vitae tellus scelerisque rhoncus. Vivamus vel augue consectetur urna viverra suscipit. In lacus eros, dictum bibendum tortor rhoncus, commodo venenatis tellus. Praesent quis tristique dolor.
Morbi mauris elit, suscipit ac pretium quis, sodales in dui. Proin tempor eu quam vitae sollicitudin. Maecenas vulputate molestie tortor, id suscipit odio auctor fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sem sem, iaculis sed enim sit amet, volutpat porta metus. In sit amet massa nisi. In consectetur orci quam, consequat finibus enim viverra a. Vestibulum convallis vulputate mollis. Fusce eget enim iaculis, ultrices felis at, tincidunt diam. Vestibulum blandit tortor velit, in suscipit lorem aliquet sed.
In egestas est a sagittis viverra. Nullam et tortor ullamcorper, pretium mauris et, aliquet risus. Nullam maximus libero vitae justo blandit hendrerit. Sed quam nunc, tempus eu eleifend ac, ultrices vel odio. Aenean sit amet gravida odio. Nullam a metus elit. Curabitur varius pharetra arcu id sodales. Donec tincidunt convallis volutpat. Donec placerat lorem convallis metus sagittis eleifend. Nam convallis tellus id gravida viverra. Proin eget congue felis.
Aliquam erat volutpat. Nulla pretium velit augue, vel convallis purus egestas vel. Praesent eu nunc et nisl venenatis consectetur id eget est. Etiam ac tortor in velit dignissim viverra. Duis eros leo, tristique in vestibulum vitae, semper in lectus. Morbi at nisl at dui interdum pretium non sit amet ex. Morbi vel sodales leo. Quisque lectus diam, ullamcorper nec nulla ut, ornare placerat eros. Nam sodales consequat porta. Maecenas dictum auctor tincidunt. Nullam maximus mauris nibh, eget molestie justo vestibulum vitae. Nulla imperdiet vehicula erat, quis gravida enim interdum a. In hac habitasse platea dictumst. Fusce ac metus tortor. Curabitur auctor elementum ex, a feugiat metus sodales sit amet. Cras mollis sodales accumsan.
Curabitur suscipit, nulla nec pharetra ullamcorper, libero quam dapibus quam, vitae fringilla est metus non tellus. In pellentesque convallis metus, nec sagittis dolor ultricies ac. Vestibulum mauris justo, egestas sit amet risus a, ultricies iaculis nulla. Donec auctor tincidunt felis vel elementum. Sed interdum aliquam ex eu cursus. Mauris sollicitudin enim odio. In iaculis id nulla nec vestibulum. Mauris quam purus, pharetra vehicula mollis suscipit, eleifend eu sem. Sed condimentum massa ac lorem mattis hendrerit. Integer interdum tellus in velit dapibus ultricies. Cras vel justo nec tortor fermentum luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non interdum ex. Mauris vel dolor mauris.
Nunc sit amet libero feugiat lectus gravida mattis. Duis fermentum nisl non sapien gravida, non faucibus dui ultrices. Sed vel ullamcorper massa. Sed risus tortor, porttitor nec accumsan ac, mollis at risus. In condimentum ullamcorper lectus, a convallis sapien congue in. Cras sodales elit at dapibus congue. Donec eu purus fermentum, sollicitudin elit vel, suscipit enim. Cras dignissim sodales nibh non finibus. Sed posuere velit quis mollis efficitur.
Suspendisse eget massa vitae velit luctus efficitur sit amet ac eros. Etiam egestas, turpis vel pharetra laoreet, lacus sapien porta mauris, eget sagittis magna lacus eget velit. Sed ut finibus lorem. Aenean in justo posuere nunc pellentesque commodo in eget eros. Mauris faucibus mauris velit. Nullam eu tristique nulla. Etiam ut felis ante. Donec sit amet justo nec metus mollis efficitur sed sit amet quam. Pellentesque eget sapien maximus, efficitur odio sed, mollis magna. Curabitur tincidunt eu elit eu venenatis.
Cras porta lorem odio, venenatis ornare lorem gravida ut. Duis congue accumsan vehicula. Vivamus placerat tellus nec mattis placerat. Donec nisi elit, ultricies ac ultrices vitae, ultricies vitae eros. Praesent interdum, odio vel vestibulum aliquet, risus urna scelerisque leo, ut maximus sem urna non ligula. Cras sit amet metus aliquet, pharetra quam vel, venenatis enim. Curabitur dictum purus dui, sed facilisis neque venenatis id.
Integer in ante in nunc condimentum efficitur vitae nec lacus. Phasellus a pretium mauris. Integer eget metus mi. Cras vitae tortor vel ante mattis porttitor. Praesent efficitur est mi, in posuere turpis tincidunt et. Nullam ex libero, rutrum vitae orci at, placerat tempus velit. Quisque consectetur vel leo id pharetra. Aliquam eu hendrerit libero, eu tristique ligula. Mauris in porta mauris. Sed tempus, velit ut convallis ullamcorper, metus mi commodo felis, sit amet sollicitudin est metus id tortor.
Morbi tristique ultricies magna nec congue. Pellentesque vel augue non orci sollicitudin laoreet in et mauris. Ut sed enim sollicitudin dui eleifend laoreet eu ornare lectus. Sed euismod quam eu magna congue commodo. Maecenas sit amet nisl finibus, auctor nulla vitae, condimentum augue. Vestibulum mattis, lorem convallis rhoncus pharetra, ante nisl ultricies libero, sit amet ullamcorper nisi sem et nulla. Integer elit lorem, iaculis non sem et, volutpat auctor est. Donec non erat ante. Quisque id pretium elit. Duis urna nunc, eleifend ut vulputate non, posuere eu lectus. Nulla sed mauris id leo rhoncus vulputate quis vitae velit. Etiam non est est. Integer bibendum, risus at ultricies imperdiet, metus turpis efficitur elit, a eleifend tortor eros a dolor. In hac habitasse platea dictumst. Maecenas eleifend venenatis lorem, ut viverra felis dignissim sit amet.
Nunc hendrerit quis massa id convallis. Vivamus imperdiet vehicula dui, id viverra arcu suscipit et. Nulla congue metus sit amet lorem varius porttitor. Maecenas a erat nulla. Etiam tristique turpis a dui imperdiet pretium. Nam dolor tellus, lacinia non dolor mollis, iaculis porta risus. Suspendisse a mi ut dolor ultricies posuere. Nunc viverra consectetur urna, ut porttitor turpis vulputate non. Donec at tincidunt augue, in fringilla risus. Morbi posuere odio eget magna condimentum vestibulum. Nullam at placerat libero, in fermentum eros. Vivamus a accumsan nulla. Integer consequat accumsan dolor ut mollis.
Quisque id tempus erat. Aenean venenatis tellus tempus erat fermentum semper. Vestibulum non felis dignissim, aliquet mi ut, mollis velit. Phasellus congue purus vestibulum, finibus lacus sit amet, elementum dolor. Mauris iaculis porttitor orci et luctus. Suspendisse cursus volutpat ultrices. Mauris vel auctor nisl. Ut sollicitudin in libero non pellentesque. Pellentesque sed scelerisque mauris. Aliquam rutrum vel mauris tempor semper. Duis pretium vel dui et auctor. Nunc id augue leo.
Aenean nisl ligula, consectetur venenatis pulvinar et, interdum a lacus. Maecenas ac sapien volutpat magna volutpat euismod. Suspendisse congue commodo dolor, sed blandit tortor facilisis vulputate. Aenean tristique porttitor lorem at consequat. Donec euismod metus vitae hendrerit accumsan. Vestibulum nibh nulla, congue vel aliquet quis, tempus a libero. Fusce lacinia libero ut leo mollis molestie. Quisque facilisis ipsum sed sem faucibus malesuada. Maecenas a malesuada risus. Nam tellus metus, maximus non elit a, suscipit gravida justo. Proin at aliquam sem, in fringilla erat.
Aliquam sit amet erat a purus volutpat maximus. Donec tristique feugiat semper. Etiam eu tempor leo. Vestibulum pharetra urna sollicitudin, rutrum erat nec, rutrum neque. Ut elementum mauris nec vestibulum venenatis. Pellentesque eget urna aliquet, molestie ipsum sagittis, vestibulum lorem. Duis tincidunt, sapien eu finibus laoreet, mi neque volutpat sem, ac tincidunt ex diam eu tortor. Curabitur sit amet efficitur felis, a bibendum lacus. Fusce ac varius mauris, at suscipit sem. Pellentesque commodo dolor ac nulla euismod dictum.
Cras vel elit nec dolor malesuada tempus. Donec vel tincidunt magna. Maecenas eget eros turpis. Praesent sit amet tortor nunc. Cras ullamcorper semper risus, suscipit gravida nulla scelerisque venenatis. Integer mollis euismod magna, faucibus tristique lacus sagittis id. Suspendisse sed nulla id quam tempus gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis purus quis lectus fermentum porta. In turpis mauris, scelerisque eu bibendum nec, mollis quis ante. Ut laoreet mauris arcu, a suscipit massa pellentesque in. Mauris pretium, eros at aliquam pulvinar, leo est vulputate leo, in fringilla turpis velit quis leo. Praesent eu urna congue, gravida augue sagittis, sagittis ante. Nam pretium lobortis rutrum. Duis maximus, nulla eu volutpat viverra, elit ex egestas nunc, at lacinia dolor magna sit amet dolor.
In suscipit ultricies nisl ac sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras a sollicitudin turpis. Sed ornare risus nulla, mattis lacinia odio dictum eget. Nam varius semper ante, eget luctus nisi accumsan id. In hac habitasse platea dictumst. Pellentesque maximus, nunc non vestibulum efficitur, magna leo scelerisque tellus, vel accumsan nulla turpis at nulla. Vivamus egestas nunc quis libero suscipit dapibus. Nullam id porta augue. Vestibulum pulvinar tellus a lectus fermentum euismod. Vivamus facilisis erat vitae odio feugiat vestibulum. Phasellus efficitur, tellus sed feugiat consectetur, augue ex faucibus mauris, sed pretium est risus dignissim libero. Cras ultricies et urna sit amet pretium. Integer at felis sem. Proin at eros sed lacus volutpat cursus.
Vestibulum porttitor malesuada mi. Vivamus eget nulla ut arcu malesuada gravida. Vivamus fermentum arcu at orci semper, vel consectetur nunc fringilla. Sed fermentum ut mauris vel sodales. Aliquam ornare, ligula ac fringilla dignissim, sem urna semper sapien, sit amet consectetur nibh arcu nec nulla. Nulla facilisi. Aenean tincidunt consectetur erat, ultrices dapibus ex finibus et. Vestibulum blandit gravida orci, eu bibendum leo mollis vel. Morbi quis lorem justo. Vestibulum laoreet eros tellus, ac tristique mauris congue sed. Donec sed aliquet eros, eget blandit sapien.
Maecenas eu mi neque. Etiam finibus leo tellus, at venenatis augue ullamcorper vel. Curabitur dignissim ornare lorem. Nunc vestibulum, sapien eget varius commodo, enim diam sagittis orci, et scelerisque eros odio id ex. Maecenas ac sapien consequat, tincidunt tellus at, sagittis mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum id tincidunt nunc. Sed in rutrum neque. Cras vitae nisl elit. Praesent sagittis tempus dui, id elementum elit elementum at. Sed in fermentum tortor, eget imperdiet ligula. Suspendisse nulla nunc, convallis quis maximus sed, posuere et ante. Suspendisse placerat dui non eros auctor feugiat. Nulla facilisis, nunc quis mollis pharetra, enim libero fermentum libero, ut sollicitudin diam arcu imperdiet felis.
Nunc imperdiet velit vel sapien venenatis, at finibus purus feugiat. Fusce lobortis varius viverra. Morbi ac nibh in lacus ullamcorper efficitur vitae sit amet tortor. Cras tortor diam, ultrices et purus ut, placerat consequat eros. Mauris convallis quam et ullamcorper fringilla. Phasellus lobortis tellus mauris, in consequat libero hendrerit sit amet. Fusce sagittis, massa nec volutpat porta, mauris nunc lacinia nulla, vitae faucibus risus urna eget ex. Duis aliquam sodales mi vel semper. Donec egestas mi non sapien pretium, quis condimentum erat dapibus. Suspendisse eu nibh mauris. Ut vel dui nunc. Mauris cursus nibh nibh, vitae dictum ante feugiat vitae. Morbi aliquet scelerisque dictum. Sed quis sapien volutpat, luctus odio sed, volutpat lorem. Vestibulum rutrum sem lacus, ac dictum ex lacinia quis. Sed sodales turpis quam, a porta lectus pharetra quis.
Vestibulum a ex id mi ultricies sagittis. Nunc eget risus nec nibh tempor suscipit sed non felis. Vestibulum aliquam, massa ac rutrum congue, elit nibh vehicula diam, quis porta quam velit nec libero. Sed lorem diam, finibus at commodo in, eleifend ac ipsum. Proin nec porta massa, id tempor nulla. Praesent odio dui, tincidunt ut rhoncus a, condimentum non neque. In et nisl nec neque pretium luctus. Aliquam in nisl nibh.
Nam porta consectetur ex, sed blandit tortor consectetur sed. Phasellus et sem pretium, mollis elit id, interdum dolor. Nam viverra libero purus, et pellentesque magna congue quis. Vivamus a rutrum turpis. Donec non fringilla nunc. Etiam vel nulla sit amet metus bibendum porttitor ut sit amet augue. Aliquam erat volutpat. Aliquam vitae nisi ut velit rhoncus rhoncus a ac metus. Proin elementum ante et felis ornare, at tempor orci efficitur. Maecenas feugiat nibh non elit finibus, id dignissim arcu finibus.
Donec elit libero, bibendum non ornare eu, fermentum eu ligula. Pellentesque ut augue at ante tempor pulvinar. Ut sed mi eget augue ultrices gravida. Nulla vel accumsan est, id tempus elit. Phasellus tempor, quam lacinia blandit scelerisque, dolor est tempor ex, sed aliquet neque purus a nibh. Aenean ligula est, dignissim varius leo quis, vehicula ultrices lorem. Fusce erat lorem, dignissim et interdum vitae, maximus vitae sem. Vivamus gravida sapien a lorem gravida, ut finibus elit laoreet. Ut odio sem, facilisis sed tempus sed, pharetra faucibus nisl. Ut ut pulvinar lacus. Integer eros ex, mattis ac feugiat ac, laoreet in mi. Vestibulum eleifend, magna pellentesque venenatis dignissim, lectus erat sagittis massa, nec rhoncus diam sapien vel turpis. Nam sollicitudin dapibus eros, in iaculis lacus tempus ac.
Aenean fringilla a velit eu efficitur. Duis a condimentum lectus. Cras congue eros vel sapien molestie fringilla. Morbi quis placerat nibh. In vel pellentesque ex. Morbi non ornare libero, nec dictum elit. Integer non volutpat est, rhoncus commodo elit. Duis mattis molestie diam, fringilla efficitur lorem vehicula ut. Cras convallis facilisis urna a finibus. Nulla cursus ligula quis tellus dignissim, eu lobortis justo ultrices. Proin et luctus tellus. Phasellus sit amet ornare dui. Vestibulum lacinia lacus quis neque scelerisque dignissim id id mi. Mauris interdum fermentum urna, nec hendrerit massa gravida ut. Nullam interdum ac nisi ut elementum. Nullam ac massa turpis.
Aenean gravida, diam at lacinia semper, quam diam scelerisque odio, sed ultricies enim quam non mi. Vivamus lacinia eros gravida lacus porttitor feugiat. Proin sodales eget ligula in pharetra. Ut eleifend maximus fermentum. Donec massa nunc, commodo sit amet aliquam eget, tristique in tellus. Ut tortor purus, rutrum non hendrerit vitae, malesuada non ligula. Sed non lorem quam. Integer metus magna, pretium vel pretium sed, semper ut diam. Nullam malesuada porta nisl et hendrerit. Proin viverra neque vel ornare mattis. Morbi viverra nunc quis turpis molestie, at faucibus nibh vulputate. In ultrices venenatis elit ut sollicitudin. Curabitur a nisi ut nunc congue aliquam et imperdiet nibh. Morbi luctus egestas eros et ultricies.
Maecenas scelerisque lorem quis mauris hendrerit, quis cursus purus tristique. Nunc vehicula sit amet odio et vehicula. Donec a imperdiet purus, ut tempus massa. Donec sodales massa lacus. Nulla porta rhoncus ipsum, vitae sollicitudin magna posuere non. Morbi aliquet varius orci eget ultricies. Aliquam consequat sagittis fermentum. Proin ullamcorper eros quis urna ultricies, in ullamcorper libero feugiat. Integer vel turpis vestibulum, facilisis urna at, venenatis tortor. Pellentesque enim ex, bibendum a tempus in, aliquam ut libero. Fusce sagittis, elit sed tempor facilisis, erat risus lobortis purus, ac sagittis dolor libero ac nulla. Etiam congue varius nisi, at malesuada nibh fringilla ac. Vestibulum laoreet mi eleifend quam ultricies porttitor. Proin tincidunt tortor sed neque ullamcorper porta. Nunc quis lectus quis ligula ultrices pretium. Nulla nec condimentum neque, et tempor leo.
Duis pellentesque ligula ac mi laoreet, laoreet facilisis turpis condimentum. Ut et est sed eros suscipit blandit vel ac nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas dignissim, mauris ac porttitor ullamcorper, dui tellus varius mi, et mollis urna justo sed quam. Donec euismod suscipit nisi vitae pulvinar. Nullam est arcu, pharetra a pretium sed, egestas sed purus. Suspendisse faucibus pellentesque nibh, a aliquet felis tempor in. Nunc nec felis non urna dapibus semper in at lectus.
Praesent neque est, ullamcorper non feugiat eu, egestas rutrum tellus. Sed a vehicula magna. Nam nisi risus, fermentum in nulla et, consectetur tincidunt purus. Praesent ut vulputate ipsum, ac eleifend ipsum. Integer sed interdum mi. Sed consectetur est at neque aliquet tincidunt. Pellentesque consequat dolor a diam egestas, vel efficitur neque dapibus. Nunc tincidunt, tortor eu tincidunt placerat, eros velit condimentum ipsum, quis tempor metus dui vel ipsum. Aenean varius commodo sollicitudin.
Etiam nisi justo, pretium ac augue eu, tincidunt elementum dui. Maecenas sed elit ligula. Etiam elit lectus, imperdiet a consectetur sed, efficitur eget lacus. Morbi pulvinar orci lobortis mi condimentum congue. Nunc tincidunt, libero vel vehicula finibus, odio enim fermentum metus, vitae mollis arcu dolor nec mauris. Maecenas finibus pretium est id cursus. Sed nec orci sollicitudin, fermentum felis eu, lobortis mi. Curabitur erat ex, maximus ut leo volutpat, gravida malesuada urna. In at lectus dictum arcu consectetur ullamcorper. Donec vestibulum turpis vitae nisl posuere, non scelerisque nulla tincidunt. Maecenas eleifend, risus id egestas pulvinar, ante lacus varius tellus, id viverra felis tortor quis lacus. Phasellus pharetra urna massa, et fringilla lectus bibendum vel. Maecenas consequat cursus enim, a blandit risus tempor non. Pellentesque congue dictum mollis. Nunc sed diam ultrices, tristique libero sed, semper leo.
Cras consequat, tortor ut dignissim aliquet, ligula ipsum sagittis erat, vel hendrerit tortor nibh et odio. Maecenas at euismod ante, id mattis nisl. Nullam a eleifend sem. Nam eleifend condimentum hendrerit. Aliquam erat volutpat. Cras posuere ipsum est, eget rhoncus neque fermentum ac. Curabitur et consequat orci, vitae dapibus urna. In hac habitasse platea dictumst.
Mauris ultricies varius nunc vehicula vestibulum. Nam condimentum at sem in ultrices. Curabitur eleifend sem eu lacus porttitor scelerisque. Proin sit amet egestas ante. Aenean venenatis convallis dolor, eget aliquet nibh volutpat ultrices. Donec vitae ipsum ante. Vivamus eu nibh nec ex viverra rutrum non id tortor. Curabitur faucibus feugiat iaculis. Donec bibendum massa placerat est ultrices, non porta elit viverra.
Nulla faucibus egestas bibendum. Maecenas non sapien eget sapien pellentesque venenatis nec at augue. Nullam ut tempor elit. In sodales molestie nisi, at vestibulum purus venenatis ac. Vestibulum ut sagittis dui, ut ornare risus. Pellentesque pharetra tincidunt ex et vehicula. Proin vel ex non magna dignissim porttitor. Maecenas dui leo, pretium eget porta volutpat, faucibus hendrerit mi. Suspendisse varius diam id mauris varius condimentum.
Phasellus vehicula arcu quis turpis maximus, ut fringilla justo lacinia. Morbi est dui, finibus in rhoncus varius, fermentum eu nulla. Nullam eu erat ullamcorper sapien aliquam commodo. Quisque sit amet lectus metus. Phasellus placerat, risus eget viverra laoreet, nisl justo tincidunt sapien, vitae aliquet ex sapien vel metus. Nunc eget aliquam arcu. Nulla efficitur urna sed ligula ultrices, maximus aliquet tellus facilisis. Cras gravida metus vitae velit placerat, eu aliquam elit vulputate. Pellentesque ut arcu nec ante convallis interdum vitae in massa. Integer vitae quam et erat placerat vehicula.
Curabitur cursus orci non ante scelerisque, nec facilisis ante vehicula. Nulla bibendum scelerisque urna, in viverra felis maximus sed. Praesent eu cursus massa. Ut consectetur sem in ultricies dignissim. Donec elementum odio sodales facilisis luctus. Etiam quis nibh lectus. Integer molestie ante ut ex ornare pellentesque. Donec vulputate at dui at consequat. Nam eget luctus risus, quis cursus sapien. Praesent convallis arcu vitae ex ullamcorper, eu porta neque vehicula. Mauris quis ante diam. Maecenas fermentum pellentesque justo, in mattis lorem porttitor vitae.
Integer placerat scelerisque lectus ut facilisis. Sed ac ante eu risus ultrices pharetra elementum quis magna. Aliquam egestas risus mattis, aliquet risus ac, ultricies augue. Ut sollicitudin libero at nulla elementum, ac vehicula magna lobortis. Curabitur eget interdum est. Aenean commodo finibus massa nec semper. Etiam a metus enim. Pellentesque finibus elit nec sollicitudin ultrices. Morbi faucibus odio quis quam efficitur fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut gravida purus, et vehicula erat. Ut ut porttitor nunc, porta lacinia nisi. Vestibulum tellus sem, condimentum malesuada volutpat id, venenatis et dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus.
In aliquam odio nunc, at volutpat ante tincidunt non. Pellentesque nec tincidunt dui. Ut facilisis aliquam libero sed pretium. Nullam placerat, neque non varius mattis, est metus aliquet mauris, eu tincidunt tortor dolor sed nisl. Fusce in metus id odio tempor suscipit vel at justo. Donec nec finibus quam. Nullam non mi gravida, consequat dolor mattis, lobortis tellus. Phasellus tincidunt velit in tellus suscipit tincidunt. Sed in ultricies arcu, et fermentum felis. Nam vel dapibus urna. Praesent tempus gravida urna, quis laoreet metus fringilla quis. Curabitur blandit eleifend nulla in pellentesque.
Quisque imperdiet dictum nulla. Etiam rhoncus augue eu quam venenatis commodo. Ut sit amet nunc non leo fermentum vestibulum vel sit amet urna. Nulla ac orci eleifend justo aliquet pellentesque et eu lorem. Aliquam vehicula diam ut quam ultrices consectetur. Suspendisse faucibus diam sit amet lectus varius accumsan. Nunc hendrerit id elit in pharetra.
Mauris mi elit, vehicula ut ullamcorper non, vulputate vitae purus. Vivamus est purus, mollis nec vehicula eu, aliquam eu urna. Pellentesque aliquam fermentum porttitor. Donec velit ipsum, venenatis sit amet nisi et, molestie placerat magna. Nunc molestie lectus vitae mauris molestie, ac tincidunt elit varius. Donec varius sodales dolor, non varius dui laoreet eget. Nullam sed tellus quis nisl tempus sodales. Aliquam eu eros quam.
Nulla dapibus blandit luctus. Etiam pharetra ante a eros bibendum dictum. Duis eleifend quam eleifend, malesuada mauris pharetra, auctor nulla. Integer lorem nunc, rhoncus sit amet accumsan non, faucibus non nisi. Aenean pharetra, quam at pellentesque faucibus, ante sapien volutpat turpis, sed sagittis metus lorem sed dolor. Sed sollicitudin porta lobortis. Vivamus eu fringilla magna, in rutrum lectus. Integer auctor, urna vitae mollis facilisis, diam tellus tempor est, quis placerat lacus ligula sed lorem. Vestibulum lobortis vel nisi vel eleifend. Fusce massa augue, tincidunt sit amet urna vitae, scelerisque pellentesque est. Ut sed metus ac nulla ullamcorper bibendum vitae sed est. Aenean mattis, metus in rhoncus tincidunt, lectus ligula rhoncus risus, consequat rhoncus quam risus non urna. Vivamus diam augue, tincidunt ac nisi id, egestas ultricies odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam mauris leo, mollis id dolor vitae, scelerisque semper turpis.
Sed vitae ex tellus. Mauris quis eleifend leo. Integer malesuada mollis massa id dignissim. Curabitur eu auctor sem. Proin vel tortor augue. Sed imperdiet finibus rhoncus. Nam cursus a metus at rutrum. Nunc finibus ligula tortor, non bibendum quam bibendum vel. Ut imperdiet nunc odio, sed suscipit erat imperdiet commodo. Vestibulum nec nulla rutrum, sagittis velit a, placerat ipsum. Cras maximus, leo eu congue interdum, nibh tortor lacinia dui, sed congue dui enim a risus. Morbi cursus et ex dapibus mollis. Mauris gravida elit nibh, a elementum lectus tempus eget. Curabitur maximus a tortor vel viverra. Suspendisse potenti. Pellentesque placerat diam et sollicitudin laoreet.
Aliquam erat volutpat. Nulla porta interdum viverra. Nulla pellentesque arcu venenatis porttitor auctor. Maecenas rhoncus erat in massa ultrices eleifend. Quisque elementum purus magna, eu elementum mauris gravida in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla et sodales nulla. Pellentesque aliquam augue sit amet mi fermentum efficitur. Pellentesque tortor massa, vestibulum nec rhoncus sit amet, convallis in tortor. Curabitur vel massa lorem.
Pellentesque sit amet efficitur tortor. Sed volutpat mauris vitae libero sodales, a mollis turpis condimentum. Sed dictum, eros vel congue pretium, erat arcu interdum mi, et cursus orci diam nec urna. Aenean tempus bibendum augue eget mollis. Aliquam convallis auctor mollis. Pellentesque porttitor mauris accumsan, condimentum felis eget, consequat neque. Morbi justo tellus, lacinia eu vulputate dapibus, commodo vel erat. Nam dapibus interdum magna, ac fringilla purus vulputate ac.`

	text = strings.ReplaceAll(text, ",", "")
	text = strings.ReplaceAll(text, ".", "")

	t := NewTrie()
	for _, v := range strings.Fields(text) {
		t.Add(v)
	}

	return t
}
